### ISSUE TITLE
Improve error message for missing pass otp extension

### ISSUE THREAD

**Issue by DamienCassou** [volrath/password-store-otp.el#1]
I think this is a bit rough:

https://github.com/volrath/password-store-otp.el/blob/78673ae978962bad8d6f684fa79c2eff670f92e8/password-store-otp.el#L98

What about adding a link (https://github.com/tadfisher/pass-otp) to the project?

**Comment by volrath** [comment]
@DamienCassou Not sure I understand what do you mean by rough. I'm following [emacs convention](https://www.gnu.org/software/emacs/manual/html_node/elisp/Signaling-Errors.html) of stating what's wrong, but not how things ought to be. Do you have a particular improvement in mind?

Regarding the link, there's already a link to `pass-otp` in the README file. Do you mean add it to the error message as well?

**Comment by DamienCassou** [comment]
What about

> Error: pass extension 'pass-otp' is not installed

? With this, we at least get the name of the extension and the user knows what to search for.

**Comment by volrath** [comment]
Perfect! thanks.
